[package]
name = "plotters-gpui"
version = "0.1.0"
edition = "2021"
authors = ["Jakku Sakura <qjk2001@gmail.com>"]
repository = "https://github.com/JakkuSakura/plotters-gpui"
description = "Plotting with gpui in Rust"
license = "MIT"

[dependencies]
plotters-backend = "0.3.7"
gpui = { git = "https://github.com/zed-industries/zed" }
parking_lot = "0.12.3"
plotters = { version = "0.3.7", optional = true }
tracing = "0.1"

[dev-dependencies]
chrono = "0.4"
anyhow = "1"
rand = "0.8.3"
rand_distr = "0.4.0"
rand_xorshift = "0.3.0"
sysinfo = "0.33"

[features]
default = ["plotters"]
plotters = ["dep:plotters"]
